title: dev-tae.github.io
description: >- # this means to ignore newlines until "baseurl:"
  Write your awesome description for your site here. It will appear in your
  document head meta (for Google search results) and in your feed.xml site
  description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

markdown: kramdown
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one
