title: dev-tae.github.io
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my code progression note, where I document the milestones of my ongoing quest to enhance my skills as a software engineer. Here you’ll find a chronicle of my adventures in code, from solving algorithmic challenges to exploring new programming paradigms.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

markdown: kramdown
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one
